title: Michael a.k.a. StarChar
description: "Website About Michael"
url: "https://michaelholmblad.com"

author:
  name: "Michael Holmblad"
  email: "mholmblad13@gmail.com"

baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
paginate: 5

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0.0"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
